# Configuration file that shows default settings
# By default, a `config.toml` file in the same directory will be merged with this file and override the default settings.
# You can override this location by either using the `--config-file` parameter
# or setting the `EAS_WEATHER_RS__APP__CONFIG_FILE` environment variable.

[logging]
format = "text"               # Log formatting ["text", "json"]
trace_level = "info"          # Log level ["error", "warn", "info", "debug", "trace"]

[webserver]
hostname = "localhost"      # Server host
#base_path = "/"             # Base path for API
port = 8080                 # Server port

shutdown_timeout_secs = 5   # Graceful shutdown timeout in seconds

default_page_limit = 10    # Default page size for paginated endpoints
page_limit_max = 100       # Maximum page size for paginated endpoints

[database]
# If the conn_url_file is not found, then the program will use the following value for
# the connection string.
conn_url_file = "./config/mysql_conn_url"   # Database connection URL file path

conn_max_retries = 5                        # Maximum number of connection retries
conn_retry_init_delay_secs = 1              # Initial delay between connection retries in seconds, exponential backoff

conn_acquire_timeout_secs = 5               # Maximum amount of time to spend waiting per connection attempt in seconds
conn_idle_timeout_secs = 300                # Idle connection timeout in seconds
conn_max_lifetime_secs = 1800               # Maximum lifetime of a connection in seconds

min_connections = 1                         # Minimum number of database connections in the pool
max_connections = 151                       # Maximum number of database connections in the pool
